[package]
name        = "somnium_ui"
description = "Native retained UI toolkit and Nocturne editor chrome for the Somnium Engine."
version.workspace      = true
edition.workspace      = true
rust-version.workspace  = true
license.workspace      = true
authors.workspace      = true

[dependencies]
winit      = { workspace = true }
wgpu       = { workspace = true }
tracing    = { workspace = true }
somnium_ecs = { path = "../somnium_ecs" }
somnium_asset = { path = "../somnium_asset" }
glam       = { workspace = true }
bytemuck   = { workspace = true }
fontdue    = { workspace = true }
resvg      = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
