//! Link the engine mark into the executable as a Windows icon resource.
//!
//! MORROWIND-J step 2. `WindowAttributes::with_window_icon` covers a *running*
//! window: the taskbar button, alt-tab, the window list. It cannot cover the
//! file sitting in a folder or a shortcut pinned before the editor has started,
//! because those read an icon resource out of the binary itself.
//!
//! Failure here is a warning, never an error. The resource compiler ships with
//! the Windows SDK, and a machine that can build this engine but happens not to
//! have `rc.exe` should still get an engine — with the system's default file
//! icon, which is what it had before this file existed.

fn main() {
    // The `.ico` is regenerated by `cargo run -p somnium_ui --example
    // brand_icon`; see `crates/somnium_ui/assets/brand/PROVENANCE.md`.
    const ICON: &str = "../../crates/somnium_ui/assets/brand/somnium.ico";
    println!("cargo:rerun-if-changed={ICON}");
    println!("cargo:rerun-if-changed=build.rs");

    #[cfg(target_os = "windows")]
    {
        if !std::path::Path::new(ICON).exists() {
            println!("cargo:warning=brand icon missing at {ICON}; building without a file icon");
            return;
        }
        let mut resource = winresource::WindowsResource::new();
        resource.set_icon(ICON);
        resource.set("ProductName", "Somnium Engine");
        resource.set("FileDescription", "Somnium Engine");
        if let Err(error) = resource.compile() {
            println!("cargo:warning=icon resource not linked ({error}); the binary still builds");
        }
    }
}
