[package]
name = "somnium_physics"
description = "Safe Rust wrapper around JoltPhysics for the Somnium Engine."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
somnium_physics_sys = { workspace = true }
glam = { workspace = true }
tracing = { workspace = true }
