//! Phase 16-F: type declarations for the script API, generated from the
//! component registry.
//!
//! # One registry, and this is the fourth consumer
//!
//! The plan's fourth goal is that the schema registry built in 16-A powers
//! script bindings, scene serialization, the editor's field UI and this.
//! Nothing in this file lists a component or a field; it walks
//! [`TypeRegistry`] and prints what is there. Adding a component to the
//! engine is one `component_schema!` block, and the declarations follow.
//!
//! # What this is honestly worth
//!
//! It produces a `.d.luau` that describes `ctx`, the command surface and
//! every registered component. What it does **not** do is prove that a
//! Luau type-checker accepts it: `luau-analyze` is a separate binary that
//! this engine does not vendor and CI does not have, so a test claiming
//! "the declarations type-check" would be claiming something nobody ran.
//! The tests here assert the shape and the coverage — that every
//! registered component appears, with every script-visible field, at the
//! right type — which is what can actually be checked.
//!
//! The common Luau LSP frontend is community-maintained and is not an
//! official Luau tool. The help page says so; first-class IDE support is
//! not claimed.

use std::fmt::Write as _;

use somnium_ecs::reflect::{FieldFlags, FieldType, TypeRegistry};

/// The `.d.luau` for the whole script-facing API.
#[must_use]
pub fn generate_declarations(registry: &TypeRegistry) -> String {
    let mut out = String::with_capacity(8 * 1024);
    out.push_str(HEADER);
    write_components(&mut out, registry);
    out.push_str(CONTEXT);
    out
}

/// The parts that do not come from the registry: the handles, the value
/// types and the shape of `ctx`.
const HEADER: &str = r"--!strict
-- Generated by Somnium. Do not edit.
--
-- Regenerate with `SOMNIUM_WRITE_DECLS=1` on any run of the editor, or
-- from `somnium_core::script_decls::generate_declarations`.
--
-- Note: the Luau language server most editors use is community
-- maintained and is not an official Luau tool. These declarations are
-- generated from the same component registry the engine, the scene
-- format and the Details panel read, so they cannot drift from it — but
-- whether your editor understands them is between you and your editor.

--- An entity reference. Opaque: it cannot be constructed from a number,
--- and arithmetic on it is an error.
export type Entity = userdata

--- A content asset reference. Opaque, for the same reason.
export type Asset = userdata

--- A placeholder for an entity that does not exist yet. Resolves through
--- `ctx.spawns` on the next phase.
export type SpawnToken = number

export type Vec2 = { x: number, y: number }
export type Vec4 = { x: number, y: number, z: number, w: number }
export type Quat = Vec4
--- Three floats. Built with `vector.create(x, y, z)`.
export type Vec3 = vector
--- Linear RGB.
export type Color = vector

--- CONTROL-K. One key of an authored curve. Read-only from a script: the
--- editor authors curves, and a script that assigned a table back would be
--- rejected by the field's declared type rather than silently accepted.
export type CurveKey = {
    t: number,
    v: number,
    inTangent: number,
    outTangent: number,
    interpolation: string,
}

--- CONTROL-K. One stop of an authored colour ramp. Read-only, as above.
export type GradientStop = { t: number, color: Color, alpha: number }

";

/// `ctx`, the input helpers and the command surface.
const CONTEXT: &str = r#"
--- Named gameplay actions as a fixed step sees them. Bindings may come from
--- keyboard, mouse, or gamepad without changing script code.
export type Input = {
	actionDown: (self: Input, action: string) -> boolean,
	actionPressed: (self: Input, action: string) -> boolean,
	axis: (self: Input, action: string) -> number,
	vector2: (self: Input, action: string) -> vector,
}

--- One delivered game event.
export type Event = { name: string, sequence: number }

--- Everything a callback is handed.
---
--- Writes are deferred to the end of the phase: one script's changes are
--- invisible to another until then. Your own components, reached through
--- `self`, are a plain table and *are* visible to you immediately.
export type Context = {
	--- The entity this attachment is on.
	entity: Entity,
	--- Simulation time in seconds. Advanced only by completed fixed steps.
	time: number,
	--- Duration of one fixed step.
	fixedDelta: number,
	--- Fixed steps since the simulation started.
	step: number,
	input: Input,
	--- This entity's declared components, as plain tables. Present only
	--- for components named in `uses`.
	self: SelfComponents,
	--- Entities produced by this attachment's spawns in the previous
	--- phase, keyed by the token `spawn` returned. `nil` when there are
	--- none.
	spawns: { [SpawnToken]: Entity }?,

	isAlive: (self: Context, entity: Entity) -> boolean,
	--- Read one field of another entity's component.
	get: (self: Context, entity: Entity, component: string, field: string) -> any,
	--- Queue a write to another entity's component. Applied at the end of
	--- the phase, so reading it back before then returns the old value.
	set: (self: Context, entity: Entity, component: string, field: string, value: any) -> (),
	--- Queue a spawn. Returns a token, not an entity — the entity does
	--- not exist until the phase commits.
	spawn: (self: Context) -> SpawnToken,
	--- Queue a despawn. An entity may despawn itself; the callback
	--- finishes first.
	despawn: (self: Context, entity: Entity) -> (),
	applyForce: (self: Context, entity: Entity, force: Vec3, impulse: boolean?) -> (),
	--- Play a registered content-relative audio asset as a one-shot.
	playAudio: (self: Context, assetPath: string, volume: number?) -> (),
	--- Set a typed animation-graph parameter. Changes are deferred to the
	--- phase boundary and validated against the graph's parameter schema.
	setAnimationBool: (self: Context, entity: Entity, name: string, value: boolean) -> (),
	setAnimationFloat: (self: Context, entity: Entity, name: string, value: number) -> (),
	setAnimationInt: (self: Context, entity: Entity, name: string, value: number) -> (),
	triggerAnimation: (self: Context, entity: Entity, name: string) -> (),
	emit: (self: Context, name: string) -> (),
	log: (self: Context, ...any) -> (),
	warn: (self: Context, ...any) -> (),
	error: (self: Context, ...any) -> (),
}

--- The property descriptor builders.
declare Field: {
	boolean: (default: boolean, options: FieldOptions?) -> any,
	integer: (default: number, options: FieldOptions?) -> any,
	number: (default: number, options: FieldOptions?) -> any,
	string: (default: string, options: FieldOptions?) -> any,
	vec2: (default: Vec2, options: FieldOptions?) -> any,
	vec3: (default: Vec3, options: FieldOptions?) -> any,
	vec4: (default: Vec4, options: FieldOptions?) -> any,
	quat: (default: Quat, options: FieldOptions?) -> any,
	color: (default: Color, options: FieldOptions?) -> any,
	entity: (default: Entity?, options: FieldOptions?) -> any,
	asset: (default: Asset?, options: FieldOptions?) -> any,
}

export type FieldOptions = { min: number?, max: number?, description: string? }

--- The declaration a module returns.
declare Script: {
	define: (descriptor: ScriptDescriptor) -> ScriptDescriptor,
}

export type ScriptDescriptor = {
	apiVersion: number?,
	schemaVersion: number?,
	--- Components to mirror onto `ctx.self`. Name the fields you use:
	--- mirroring a whole component marshals every field in both
	--- directions every frame.
	uses: { [string]: { string } }?,
	fields: { [string]: any }?,

	onInit: ((self: any, ctx: Context) -> ())?,
	onStart: ((self: any, ctx: Context) -> ())?,
	onEnable: ((self: any, ctx: Context) -> ())?,
	onDisable: ((self: any, ctx: Context) -> ())?,
	onFixedUpdate: ((self: any, ctx: Context, dt: number) -> ())?,
	onUpdate: ((self: any, ctx: Context, dt: number) -> ())?,
	onEvent: ((self: any, ctx: Context, events: { Event }) -> ())?,
	onDestroy: ((self: any, ctx: Context) -> ())?,
	saveState: ((self: any) -> any)?,
	loadState: ((self: any, state: any) -> ())?,
	migrateProperties: ((self: any, props: any, fromVersion: number) -> any)?,
}
"#;

/// One Luau type per registered component, plus the `ctx.self` table that
/// gathers them.
fn write_components(out: &mut String, registry: &TypeRegistry) {
    let mut schemas: Vec<_> = registry.iter().collect();
    // Sorted so the file is the same on every run: a generated artifact
    // that reshuffles itself makes every diff useless.
    schemas.sort_by_key(|schema| schema.stable_id.as_str());

    out.push_str("-- ── Components, generated from the type registry ──────────────\n\n");
    for schema in &schemas {
        let _ = writeln!(
            out,
            "--- `{}` (schema version {}).",
            schema.stable_id.as_str(),
            schema.version
        );
        let _ = writeln!(
            out,
            "export type {} = {{",
            luau_type_name(schema.stable_id.as_str())
        );
        for field in &schema.fields {
            if !field.flags.contains(FieldFlags::SCRIPT_READ) {
                continue;
            }
            let readonly = if field.flags.contains(FieldFlags::SCRIPT_WRITE) {
                ""
            } else {
                " -- engine-owned; reading only"
            };
            let _ = writeln!(
                out,
                "\t{}: {},{readonly}",
                field.name,
                luau_field_type(&field.ty)
            );
        }
        out.push_str("}\n\n");
    }

    out.push_str("--- The components mirrored onto `ctx.self`, by their short name.\n");
    out.push_str("export type SelfComponents = {\n");
    for schema in &schemas {
        let _ = writeln!(
            out,
            "\t{}: {}?,",
            mirror_key(schema.stable_id.as_str()),
            luau_type_name(schema.stable_id.as_str())
        );
    }
    out.push_str("}\n");
}

/// `somnium.Transform` becomes `SomniumTransform`.
fn luau_type_name(stable: &str) -> String {
    stable
        .split(['.', '_'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            chars.next().map_or_else(String::new, |first| {
                first.to_uppercase().chain(chars).collect()
            })
        })
        .collect()
}

/// `somnium.Transform` becomes `transform` — the key the mirror uses.
///
/// Deliberately the same rule as the Luau backend's `mirror_key`, and the
/// declarations test asserts they agree; two rules for one name would mean
/// the generated types described a table nothing populates.
fn mirror_key(stable: &str) -> String {
    let last = stable.rsplit('.').next().unwrap_or(stable);
    let mut chars = last.chars();
    chars.next().map_or_else(String::new, |first| {
        first.to_lowercase().chain(chars).collect()
    })
}

fn luau_field_type(ty: &FieldType) -> String {
    match ty {
        FieldType::Bool => "boolean".into(),
        FieldType::I64 | FieldType::F64 => "number".into(),
        FieldType::Str => "string".into(),
        FieldType::Vec2 => "Vec2".into(),
        FieldType::Vec3 => "Vec3".into(),
        FieldType::Vec4 => "Vec4".into(),
        FieldType::Quat => "Quat".into(),
        FieldType::Color => "Color".into(),
        FieldType::Entity => "Entity?".into(),
        FieldType::Asset => "Asset?".into(),
        // An enum crosses as its index. Naming the variants in a comment
        // rather than a union type keeps the declaration honest: the
        // engine accepts any integer in range, not only the spellings.
        FieldType::Enum(names) => format!("number --[[ {} ]]", names.join(" | ")),
        FieldType::Array(inner) => format!("{{ {} }}", luau_field_type(inner)),
        // CONTROL-K. Curves and gradients cross as read-only arrays of key
        // tables; see `convert.rs`. The declaration says so in the type so a
        // script author is not led into trying to assign one back.
        FieldType::Curve => "{ CurveKey }".into(),
        FieldType::Gradient => "{ GradientStop }".into(),
    }
}

/// Write the declarations next to the project's scripts.
///
/// # Errors
///
/// Whatever the filesystem said.
pub fn write_declarations(registry: &TypeRegistry, path: &std::path::Path) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, generate_declarations(registry))
}

/// Where the declarations go by default.
#[must_use]
pub fn default_declarations_path() -> std::path::PathBuf {
    std::env::current_dir()
        .unwrap_or_default()
        .join("assets")
        .join("scripts")
        .join("somnium.d.luau")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::reflect_registry::component_registry;

    #[test]
    fn every_registered_component_gets_a_type() {
        let registry = component_registry();
        let text = generate_declarations(&registry);
        assert!(registry.len() >= 11, "the registry should be populated");
        for schema in registry.iter() {
            let name = luau_type_name(schema.stable_id.as_str());
            assert!(
                text.contains(&format!("export type {name} = {{")),
                "`{}` has no generated type",
                schema.stable_id.as_str()
            );
        }
    }

    #[test]
    fn every_script_readable_field_is_declared_at_its_type() {
        let registry = component_registry();
        let text = generate_declarations(&registry);
        let transform = registry.by_name("somnium.Transform").unwrap();
        for field in &transform.fields {
            if field.flags.contains(FieldFlags::SCRIPT_READ) {
                assert!(
                    text.contains(&format!("\t{}: ", field.name)),
                    "`{}` is script-readable but undeclared",
                    field.name
                );
            }
        }
        assert!(text.contains("\ttranslation: Vec3,"), "{text}");
        assert!(text.contains("\trotation: Quat,"), "{text}");
    }

    #[test]
    fn an_engine_owned_field_is_marked_read_only() {
        let registry = component_registry();
        let text = generate_declarations(&registry);
        assert!(
            text.contains("engine-owned; reading only"),
            "at least one registered field is engine-owned and must say so"
        );
    }

    #[test]
    fn the_mirror_key_matches_the_backend_that_populates_it() {
        // Two rules for one name would mean these types described a table
        // nothing fills in.
        for (stable, expected) in [
            ("somnium.Transform", "transform"),
            ("somnium.Light", "light"),
            ("game.Health", "health"),
        ] {
            assert_eq!(mirror_key(stable), expected);
        }
    }

    #[test]
    fn the_output_is_stable_across_runs() {
        let registry = component_registry();
        assert_eq!(
            generate_declarations(&registry),
            generate_declarations(&component_registry()),
            "a generated file that reshuffles itself makes every diff useless"
        );
    }

    #[test]
    fn the_context_and_declaration_surface_is_described() {
        let text = generate_declarations(&component_registry());
        for expected in [
            "export type Context",
            "declare Script:",
            "declare Field:",
            "onFixedUpdate",
            "migrateProperties",
            "spawns:",
            "export type SelfComponents",
        ] {
            assert!(text.contains(expected), "missing `{expected}`");
        }
        assert!(
            text.starts_with("--!strict"),
            "a declaration file that is not strict is not much of one"
        );
    }

    #[test]
    fn an_enum_field_names_its_variants_without_pretending_to_be_a_union() {
        let text = generate_declarations(&component_registry());
        assert!(
            text.contains("number --[[ Directional | Point | Spot"),
            "the light type is an enum and should say what its numbers mean"
        );
    }
}
